spring.application.name=FoodOrderManagementSystem

#DataBase Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server Port
server.port=${PORT:8080}

# Reduce memory usage
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
