spring.application.name=FoodOrderManagementSystem

#DataBase Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/db_fms
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Som@123#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server Port
server.port=2323


# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true